const dashboardStatusMap = {
  NOT_STARTED: "لم يتم البدء",
  IN_PROGRESS: "قيد التنفيذ",
  COMPLETED: "مكتمل",
};

const tabsNames = {
  FINANCIAL: "مؤشر الأداء المالي",
  OPERATIONAL: "مؤشر الأداء التشغيلي",
  CORPORATE: "مؤشر الأداء المؤسسي",
  GENERAL: "اللوحة العامة",
};

const GOVERANCE_TABS= {
  COMPLIANCE_ADHERENCE_PRACTICES:"ممارسات الامتثال و الالتزام",
  TRANSPARENCY_DISCLOSURE_PRACTICES:"ممارسات الشفافية و الإفصاح",
  FINANCIAL_SAFETY_PRACTICES:"ممارسات السلامة المالية"

}

const entriesLabels = {
  FINANCIAL: {
    GENERAL_ADMINSTRATIVE_EXPENSES: "المصاريف العمومية و الإدارية",
    GOVERENCE_EXPENSES: "مصاريف الحوكمة",
    PROGRAMS_EXPENSES_BOUNDED: "مصاريف برامج و أنشطة مقيدة",
    PROGRAMS_EXPENSES_UNBOUNDED: "مصاريف برامج و أنشطة غير مقيدة",
    PROGRAMS_EXPENSES: "مصاريف البرامج",
    GENERAL_ADMINSTRATIVE_EXPENSES_ACT:
      "مصاريف العمومية و الإدارية المحملة على البرامج والأنشطة",
    AWQAF_EXPENSES: "مصاريف الأوقاف",
    INVESTMENT_EXPENSES: "مصاريف الاستثمار",
    SUSTAINBILITY_EXPENSES: "مصاريف الاستدامة",
    FUND_RAISING_EXPENSES: "مصاريف جمع الأموال",
    TOTAL_EXPENSES: "إجمالي المصاريف",
    AWQAF_REVENUE: "إيرادات الأوقاف",
    INVESTMENT_REVENUE: "إيرادات الاستثمارات",
    SUSTAINBILITY_REVENUE: "إيرادات الاستدامة المالية",
    BOUNDED_CHARITY: "التبرعات المقيدة",
    UNBOUNDED_CHARITY: "تبرعات غير مقيدة",
    TOTAL_CHARITY: "إجمالي التبرعات",
    CASH_RELATED: "النقد وما في حكمه",
    TRADED_INVESTMENTS: "الاستثمارات المتداولة",
    SUSTAIN_ASSETS_WAQFI: "الأصول الاستدامة الوقفية",
    SUSTAIN_ASSETS_INVEST: "أصول الاستدامة  الاستثمارات",
    SUSTAIN_ASSETS_FIN: "أصول الاستدامة المالية",
    CURRENT_LIABILITIES: "الالتزامات المتداولة",
    BOUNDED_NET_ASSETS: "صافي الأصول المقيدة",
    AWQAF_NET_ASSETS_CASH: "صافي أصول الأوقاف)نقدية)",
    GOV_PLATFORMS_REVENUE: "الإيرادات من المنصات الحكومية",
    PRGMS_PRJKS_REVENUE: "عوائد البرامج والمشاريع",
    NO_PAID_MEMBERSHIP: "عدد العضويات المسددة",
    TOTAL_MEMBERSHIP: "إجمالي العضويات",
    FIN_VALUE_VOLUN: "القيمة المالية لساعات التطوع",
    OPERATIONAL_EXPANSES: "المصروفات التشغيلية",
    LAST_YEAR_REVENUE: "إيرادات العام السابق",
    NO_CONT_VOLUN: "عدد المتبرعين المستمرين",
    NO_TOTAL_VOLUN_LAST_YEAR: "إجمالي المتبرعين في العام السابق",
    NO_TOTAL_MONEY_VAT: "إجمالي المبالغ المستردة من الضريبة",
    START_LIABILITIES: "الالتزامات في بداية العام",
    END_LIABILITIES: "الالتزامات في نهاية العام",
    TOTAL_TAX_REFUND:"اجمالي المبالغ المستردة من الضريبة"

  },
  CORPORATE: {
    COMPLIANCE_ADHERENCE_PRACTICES: "ممارسات الامتثال و الالتزام",
    TRANSPARENCY_DISCLOSURE_PRACTICES: "ممارسات الشفافية و الإفصاح",
    FINANCIAL_SAFETY_PRACTICES: "ممارسات السلامة المالية",
    NO_SUCCESSFUL_HIRES_POST_EXP:
      "عدد التعيينات الناجحة التي تجاوزت فترة التجربة",
    TOTAL_HIRES: "إجمالي التعيينات",
    PERC_COMMIT_WORK_HOURS: "نسبة الالتزام بالدوام الرسمي",
    NO_EXE_PRACTICES: "عدد التدريبات المنفذة",
    NO_PLANNED_PRACTICES: "عدد التدريبات المخططة",
    NO_COMP_ELEMENTS: "عدد العناصر المكتملة في الخطة",
    TOTAL_ELEMENTS: "إجمالي العناصر",
    NO_TIMELY_REPORTS: "عدد التقارير المنجزة في موعدها",
    NO_REQUIRED_REPORTS: "عدد التقارير المطلوبة",
    NO_GRADES_BENEFITS_SATISF: "مجموع درجات الرضا المستفيدين",
    NO_RESPONSES_SATIS_FORM: "عدد المستجيبين من استبيان رضا المستفيدين",
    TOTAL_GRADES_EMP_SATIS: "مجموع درجات رضا الموظفين",
    NO_RESPONSES_EMP_SATIS: "عدد المستجيبين من استبيان رضا الموظفين",
    TOTAL_GEADES_PARTENERS_SATIS: "مجموع درجات رضا الشركاء والموردين",
    NO_RESPONSES_PARTERS_FORM: "عدد المستجيبين من استبيان الشركاء والموردين",
    TOTAL_RESPONSES_VOL_SATIS: "مجموع درجات رضا المتطوعين",
    TOTAL_GRADES_VOL_STATIS: "مجموع درجات رضا المتطوعين",
    TOTAL_GRADES_DON_STATIS: "مجموع درجات رضا المتبرعين",
    NO_RESPOSES_VOL_SATIS_FORM: "عدد المستجيبين من استبيان رضا المتطوعين",
    NO_RESPONSES_VOL_SATIS_FORM: "عدد المستجيبين من استبيان رضا المتطوعين",
    NO_RESPONSES_DON_SATIS_FORM: "عدد المستجيبين من استبيان رضا المتبرعين",
    TOTAL_SATIS_GRADES_ORG: "مجموع درجات الرضا الجمعية العمومية ومجلس الإدارة",
    NO_ORG_MEMBERS: "العدد الكلي للأعضاء الجمعية العمومية ومجلس الإدارة",
    TOTAL_GRADES_COM: "مجموع درجات رضا المجتمع",
    NO_RESPONSES_COM_SATIS: "عدد المستجيبين من استبيان رضا المجتمع",
    TASKS_ACHIEVED_TIMELY_CEO: "المهام المنجزة في وقتها للمدير التنفيذي",
    TOTAL_PLANNED_TASKS_CEO: "إجمالي المهام المخططة للمدير التنفيذي",
    AVG_EVAL_EMPS: "متوسط تقييم أداء جميع الموظفين",
    AVG_RES_SATIS_FORMS_EMP:
      "متوسط نتائج استبيانات الرضا الموظفين، الشركاء، أصحاب المصلحة",
    EMP_EVAL: "تقييم كل موظف",
    EMP_ACHIEVMENT_PERC: "نسبه إنجاز كل موظف",
    NO_EXEC_DESC: "عدد القرارات المنفذة",
    TOTAL_DESC: "إجمالي القرارات",
    NO_ACHIV_TARGETS: "عدد الأهداف المحققة",
    TOTAL_TARGETS: "إجمالي الأهداف",
  },
  OPERATIONAL: {
    NO_OPERATIONAL_GOALS_ACHIEVED: "عدد الأهداف التشغيلية المحققة",
    NO_OPERATIONAL_GOALS_PLANNED: "إجمالي الأهداف التشغيلية المخططة",
    NO_PROGRAMS_EXECUTED: "عدد البرامج المنفذة",
    NO_PROGRAMS_PLANNED: "إجمالي البرامج المخططة",
    NO_TIMELY_ACTIVITIES: "عدد الأنشطة المنفذة في وقتها",
    TOTAL_PLANNED_ACTIVITIES: "إجمالي الأنشطة المخططة",
    APPROVED_BUDGET: "الميزانية المعتمدة",
    PLANNED_ACTUAL_DIFF: "الفرق بين المخطط والفعلي",
    NO_OUTPUTS_ACHIEVED: "عدد المخرجات المحققة بالمواصفات المطلوبة",
    TOTAL_TARGETED_OUTPUTS: "إجمالي المخرجات المستهدفة",
    NO_ACTUAL_BENEFICIARIES: "عدد المستفيدين الفعلي",
    PLANNED_TARGET_NUMBER: "العدد المستهدف في الخطة",
    NO_PROGRAMS_WITH_PARTICIPANTS:
      "عدد المشاريع والبرامج التي شارك فيها متطوعون",
    NO_PROGRAMS_PROJECTS: "إجمالي عدد المشاريع والبرامج",
    NO_TIMELY_TRANSACTIONS: "عدد المعاملات المنجزة خلال الوقت المحدد",
    TOTAL_TRANSACTIONS: "إجمالي المعاملات",
    NO_ARCHIVED_DOCS: "عدد الوثائق المؤرشفة حسب النظام",
    TOTAL_DOCS: "إجمالي الوثائق",
    NO_VOLUNTEERS_CURRENT_QUARTER: "عدد المتطوعين في الربع الحالي",
    NO_VOLUNTEERS_NEXT_QUARTER: "عدد المتطوعين في الربع السابق",
    NO_VOLUNTEERS_CONT_3: "عدد المتطوعين المستمرين لأكثر من 3 أشهر",
    TOTAL_VOLUNTEERS: "إجمالي عدد المتطوعين",
  },
  GENERAL: {
    NO_ADOPTED_ORPHANS: "عدد الأيتام المكفولين ",
    TOTAL_TARGETED_ORPHANS: "إجمالي الأيتام المستهدفين",
    TOTAL_MONTHLY_ADOP_EXP: "إجمالي تكاليف الكفالات الشهرية ",
    NO_ORPHANS_PRGM: "عدد الأيتام المشاركين في البرامج التأهيلية ",
    TOTAL_ORPHANS_QUAL_PRGM: "إجمالي الأيتام المؤهلين للبرامج التأهيلية",
    TOTAL_ANNUAL_EXP_ORPHANS: "إجمالي تكاليف الخدمات السنوية",
    NO_BENF_ORPHANS: "عدد الأيتام المستفيدين من الخدمات",
    NO_STD_ORPHANS: "عدد الأيتام الملتحقين بالتعليم العام ",
    TOTAL_ORPHANS_STD_AGE: "إجمالي الأيتام في سن التعليم العام",
    NO_ORPHANS_STD_UNI: "عدد الأيتام الملتحقين بالتعليم الجامعي ",
    TOTAL_ORPHANS_AGE_UNI: "إجمالي الأيتام في سن التعليم الجامعي",
    TOTAL_MARKS_ORPHANS: "مجموع المعدلات الدراسية لجميع الأيتام ",
    NO_GEN_EDU_ORPHANS: "عدد الأيتام الملتحقين بالتعليم",
    NO_HLTH_ORPHANS: "عدد الأيتام المشمولين بالتأمين الصحي ",
    TOTAL_ORPHANS: "إجمالي الأيتام",
    NO_EXEC_CONST_REQS: "عدد طلبات الصيانة المنفذة ",
    TOTAL_CONST_REQS: "إجمالي طلبات الصيانة المستلمة",
    NO_MOSQUES_ND_CONST: "عدد المساجد المحتاجة للترميم ",
    TOTAL_REG_MOSQUES: "إجمالي المساجد المسجلة",
    NO_MOSQUES_COMP_CONST: "عدد المساجد المكتملة البناء ",
    TOTAL_MOSQUES_PLAN_CONST: "إجمالي المساجد المخطط بناؤها",
    TOTAL_ANNUAL_EXPANSES_MOSQUES: "إجمالي تكاليف الصيانة السنوية ",
    NO_SERV_MOSQUES: "عدد المساجد المخدومة",
    NO_RESV_COMPL_MOSQUES: "عدد الشكاوى المستلمة ",
    NO_EXEC_PRJKS_MOSQUES: "عدد المشاريع المنفذة    ",
  },
};

const indicatorsLabels = {
  FINANCIAL: {
    GENERAL_ADMINSTRATIVE_EXPENSES: "المصاريف العمومية و الإدارية",
    FINANCIAL_PERF:"الأداء المالي",
    FINANCIAL_RESOURCES_DEV: "تنمية الموارد المالية",
    ADMIN_EXPENSES: "المصاريف الإدارية  ",
    PRGRMS_EXPENSES: "مصاريف البرامج و الأنشطة",
    FINANCIAL_SUSTAIN: " نسبة الاستدامة المالية ",
    DONAT_MONEY_RAISING: "جمع الأموال و التبرعات",
    ABL_COVER_OBLIG: "القدرة على تغطية التزاماتها المستقبلية",
    DIVERSITY_INCOME_RESOURCES:"تنوع مصادر الدخل",
    EFFECIENT_RESOURCE_MGMT:"كفاءة إدارة الموارد",
    ADMIN_TO_TOTAL_EXPENSES:"المصاريف الإدارية إلى اجمالي المصاريف",
    REV_FIN_SUST_TO_TOTAL_EXPENSES:"عوائد الاستدامة المالية إلى المصاريف الإدارية",
    PRGRMS_TO_TOTAL_EXPENSES:"مصاريف البرامج والأنشطة إلى اجمالي المصاريف",
    SUST_TO_TOTAL_EXPENSES:"مصاريف الاستدامة إلى اجمالي المصاريف",
    SUST_EXPENSEES_TO_REV:"مصاريف الاستدامة إلى عوائد الاستدامة",
    SUST_RETURN_TO_ASSETS:"العائد من الاستدامة إلى اجمالي أصول الاستدامة",
    FUND_RAISING_TO_TOTAL_EXPENSES:"مصاريف جمع الأموال إلى اجمالي المصاريف",
    FUND_RAISING_TO_TOTAL_DONAT:"مصاريف جمع الأموال إلى اجمالي التبرعات",
    CACHE_RELATED_TO_NET_ASSETS_AND_AWQAF:"النقد وما ي حكمه إلى (صافي الأصول المقيدة + صافي أصول النقدية الأوقاف)",
    NET_CACHE_INVEST_ADMIN_EXPENSES:"صافي النقد والاستثمارات المتداولة إلى المصاريف الإدارية التقديرية",
    DONAT_PERC:"نسبة التبرعات",
    PLATFORM_REV_PERC:"نسبة الإيرادات من المنصات",
    PRGMS_PRJKS_REV:"عوائد البرامج و المشاريع",
    PAID_MEMBERSHIP_PERC:"نسبة العضويات المسددة",
    ECO_RETURN_VOLUN:"العائد الاقتصادي من التطوع",
    RATE_REV_ANNUAL_GROWTH:"معدل نمو الإيرادات السنوي",
    COMMIT_DISC_PERC:"نسبة تخفيض الالتزامات",
    RATE_SUST_DONAT:"معدل استدامة المتبرعين",
    TOTAL_TAX_REFUND:"اجمالي المبالغ المستردة من الضريبة"
  },
  CORPORATE: {
    CORORATE_PERFORMANCE: "الأداء المؤسسي ",
    GOVERANCE: "النسبة الإجمالية للحوكمة",
    HR: "الموارد البشرية",
    PLANNING_ORGANIZING: "التخطيط والتنظيم",
    SATIS_MEASURMENT: "قياس الرضا",
    CEO_PERFORMANCE: "أداء المديرالتنفيذي ",
    COMPLIANCE_ADHERENCE_PRACTICES: "ممارسات الامتثال و الالتزام",
    TRANSPARENCY_DISCLOSURE_PRACTICES: "ممارسات الشفافية و الإفصاح",
    FINANCIAL_SAFETY_PRACTICES: "ممارسات السلامة المالية",
    RECRUITMENT: "التوظيف والاستقطاب",
    EMP_PERF_PROD: "أداء وإنتاجية الموظفين",
    EMP_DEV_TRAIN: "تطوير وتدريب الموظفين",
    TARGETS_HIT_PERF_EVAL: "تحقيق المستهدفات و تقييم الأداء ",
    JOB_COMMITMENT: "الانضباط الوظيفي",
    TRAIN_PLAN_EXEC: "تنفيذ خطة التدريب",
    TRAIN_IMPACT: "أثر التدريب",
    FOLLOWUP_OPERATIONAL_PLAN: "متابعة الخطة التشغيلية",
    QUALITY_OPERATIONAL_PLAN: "جودة الخطة التشغيلية",
    BENEF_SATIS_MEASURMENT: "رضا المستفيدين",
    EMP_SATIS_MEASURMENT: "رضا الموظفين",
    PARTENERS_SATIS_MEASURMENT: "رضا الشركاء والموردين",
    VOLUN_SATIS_MEASURMENT: "رضا المتطوعين",
    DONATORS_SATIS_MEASURMENT: "رضا المتبرعين والداعمين ",
    ADMIN_ORG_SATIS_MEASURMENT: "رضا الجمعية العمومية ومجلس الإدارة ",
    COMMUNITY_SATIS_MEASURMENT: "رضا المجتمع والصورة الذهنية",
    EXEC_LEADERSHIP: "القيادة التنفيذية ",
    OPERATIONAL_PERF: "الأداء التشغيلي",
    ENTERPRISE_COMMUN: "التواصل المؤسسي",
    FOLLOWUP_BOARD_DECISION: "متابعة تنفيذ قرارات مجلس الإدارة",
    OPERATIONAL_PLAN_ACHIVMENT_GOALS: "تحقيق المستهدفات",
    DAILY_OPS_MGMT: "إدارة العمليات اليومية",
    FOLLOWUP_EMPS_PERF: "متابعة أداء الموظفين",
  },
  OPERATIONAL: {

    EFFIC_INTERNAL_OPS: "كفاءة العمليات الداخلية",
    VOLN_MGMT: "إدارة التطوع",
    OPS_PLAN_EXEC: "تنفيذ الخطة التشغيلية",
    PRJKT_PRGM_MGMT: "إدارة المشاريع والبرامج",
    OPS_GOALS_ACH_PERC: "نسبة تحقيق الأهداف التشغيلية",
    PGRM_PRJKS_EXEC_PERC: "نسبة تنفيذ البرامج والمشاريع",
    EFFIC_PRJKS_EXEC: "كفاءة تنفيذ المشاريع",
    EFFITV_PRJKS_PGRM: "فعالية المشاريع والبرامج",
    VOLN_CONTR_PRJKS_EXEC: "مساهمة المتطوعين في تنفيذ المشاريع",
    QLY_SPEED_PROC_EXEC: "جودة وسرعة تنفيذ الإجراءات",
    DOCS_ARCHIV: "التوثيق والأرشفة",
    VOLUN_GROWTH_RATE_QUAR: "معدل النمو الربعي للمتطوعين",
    VOLUN_SUST_PERC: "نسبة استدامة المتطوعين",
    PRJKT_TIMELY_COMP_PERC: "نسبة إنجاز المشروع في الوقت المحدد",
    BUDGET_COMMIT_PERC: "نسبة الالتزام بالميزانية",
    PRJK_GOALS_ACHV_PERC: "نسبة تحقيق أهداف المشروع",
    REACH_TARGET_AUD_PERC: "نسبة الوصول للفئة المستهدفة"

  },
  GENERAL: {
    ECO_RETURN_VOLUN: "العائد الاقتصادي للتطوع",
    FINANCIAL_PERF: "نسبة الأداء المالي ",
    ADMIN_EXPENSES: "المصاريف الإدارية والعمومية",
    CORPORATE_PERFORMANCE: "نسبة الأداء المؤسسي  ",
    GENERAL_PERFORMANCE:"نسبة الأداء العام ",
    VOLUN_SATIS_MEASURMENT: "رضا المتطوعين",
    BENEF_SATIS_MEASURMENT: "رضا المستفيدين",
    ADMIN_ORG_SATIS_MEASURMENT: "رضا اصحاب المصلحة",
    TOTAL_FINANCIAL_PEFORMANCE:"نسبة الأداء المالي ",
    OPERATIONAL_PERFORMANCE:"نسبة الأداء التشغيلي ",

    GOVERANCE:"نسبة الحوكمة العامة",
    OPS_PLAN_EXEC: "تنفيذ الخطة التشغيلية",
    PRJKT_PRGM_MGMT: "إدارة المشاريع والبرامج",
    EFFIC_INTERNAL_OPS: "كفاءة العمليات الداخلية",
    VOLN_MGMT: "إدارة التطوع"
  },
};


const governanceLabels  = {
  COMPLIANCE_ADHERENCE_PRACTICES: {
 
      // Bylaws and Basic Requirements
      BYLAWS_MODIFIED_IN_CURRENT_OR_PREVIOUS_YEAR:"هل تم تعديل اللائحة الأساسية للجمعية خلال السنة المالية الحالية أو السابقة؟",
      BYLAWS_INCLUDE_MEMBERSHIP_TERMS: "هل تشتمل اللائحة الأساسية على فئات وشروط وأحكام العضوية في الجمعية العمومية؟",
      HAS_APPROVED_BYLAWS_FROM_ASSEMBLY_AND_CENTER: "هل توجد لدى الجمعية لائحة أساسية معتمدة من الجمعية العمومية والمركز الوطني لتنمية القطاع غير الربحي وفق آخر تحديث ؟",
      HAS_OFFICIAL_WEBSITE: "هل تمتلك الجمعية موقعًا إلكترونيًا خاصًا بها؟",
      HAS_VALID_COMMERCIAL_REGISTRATION: "هل يوجد لدى الجمعية سجل تجاري ساري المفعول؟",
      HAS_BRANCHES_OR_OFFICES: "هل توجد فروع أو مكاتب لدى الجمعية؟",
      HAS_PERMANENT_COMMITTEES: "هل توجد لجان دائمة في الجمعية؟",
      FOLLOWED_BYLAWS_MODIFICATION_PROCEDURES:"هل تم اتباع الاجراءات المحدّدة عند تعديل اللائحة، وقبل تحديثها واعتمادها؟",
      MEMBERSHIP_OPEN_TO_PUBLIC:"هل باب العضوية في الجمعية مفتوح للعموم؟",
      GENERAL_ASSEMBLY_MEMBERSHIP_INCREASING:"هل يوجد تزايد في عدد أعضاء الجمعية العمومية؟",
      HAS_UPDATED_MEMBERS_REGISTRY:"هل لدى الجمعية سجل متكامل ومُحدّث بأعضاء الجمعية العمومية؟",
      ELECTED_NEW_BOARD_OR_EXECUTIVE_MEMBER_IN_CURRENT_OR_PREVIOUS_YEAR:"هل انتخبت الجمعية العمومية مجلساً جديداً أو عضواَ جديداً أو عضو إدارة تنفيذية خلال السنة المالية الحالية أو السابقة؟",
      PREVIOUS_BOARD_CLEARED_IN_FIRST_MEETING_AFTER_CHANGE:"هل تم إبراء ذمة مجلس الإدارة السابق أو أحد أعضائه في الاجتماع الأول بعد تغيّر الأعضاء ؟",
      GENERAL_ASSEMBLY_MET_IN_CURRENT_YEAR:"هل اجتمعت الجمعية العمومية (الاجتماع العادي) خلال السنة المالية الحالية؟",
      GENERAL_ASSEMBLY_REVIEWED_AUDITOR_REPORT:"هل درست الجمعية العمومية العادية في اجتماعها الأول تقرير مراجع الحسابات عن القوائم المالية للسنة المالية المنتهية؟",
      GENERAL_ASSEMBLY_APPROVED_NEW_BUDGET:"هل أقرّت الجمعية العمومية العادية مشروع الميزانية التقديرية للسنة المالية الجديدة؟",
      GENERAL_ASSEMBLY_DISCUSSED_NEW_YEAR_PLAN:"هل ناقشت الجمعية العمومية العادية الخطة المقترحة للسنة المالية الجديدة واتخذت التوصيات والقرارات لذلك؟",
      SUBMITTED_MEETING_MINUTES_TO_CENTER_WITHIN_FIFTEEN_DAYS:"هل تم إرسال نسخة من محضر اجتماع الجمعية العمومية مع محضر فرز الأصوات -إن وُجد- إلى المركز خلال 15 يوماً من تاريخ الاجتماع ؟",
      HAS_CURRENT_OPERATIONAL_PLAN:"هل توجد خطة تشغيلية للسنة المالية الحالية لدى الجمعية؟",
      OPERATIONAL_PLAN_APPROVED_BY_ASSEMBLY:"هل تم اعتماد الخطة من الجمعية العمومية؟",
      EXTRAORDINARY_GENERAL_ASSEMBLY_MET_IN_CURRENT_OR_PREVIOUS_YEAR:"هل انعقدت الجمعية العمومية (غير العادية) خلال السنة المالية الحالية أو السابقة؟",
      MEETINGS_HELD_BASED_ON_VALID_REQUEST:"هل كانت الاجتماعات بناًء على طلب مسّبب من المركز، أو من مجلس الإدارة، أو بناًء على طلب عدد لا يقل عن (25%) من الأعضاء الذين يحق لهم حضور الجمعية العمومية؟",
      EXTRAORDINARY_ASSEMBLY_DISCUSSED_WITHIN_JURISDICTION:"هل كل ما تم مناقشته هو ضمن اختصاصات الجمعية العمومية غير العادّية؟",
     
      SUBMITTED_EXTRAORDINARY_MEETING_MINUTES_TO_CENTER_WITHIN_FIFTEEN_DAYS:"هل تم إرسال نسخة من محضر اجتماع الجمعية العمومية مع محضر فرز الأصوات -إن ُوجد- إلى المركز خلال 15 يومًا من تاريخ الاجتماع؟",
     
      DECISIONS_MADE_DURING_MEETING:"هل تم اتخاذ قرارات خلال الاجتماع؟",
      OBTAINED_CENTER_APPROVAL_FOR_DECISIONS:"هل تم أخذ موافقة المركز على القرارات قبل تنفيذها؟",


      HAS_INTERNAL_AUDITOR_FOR_POLICIES:"هل يوجد مراجع داخلي أو موظف التزام لمراجعة وتحديث اللوائح والسياسات الداخلية؟",
     
      HAS_INTERNAL_CONTROL_SYSTEM_FOR_SPENDING_AND_COMPLIANCE:"هل يوجد نظام رقابة داخلي لمراجعة أوامر وقرارات الصرف الداخلية ومراجعة تطابق قرارات الإدارة التنفيذية مع السياسات واللوائح الداخلية المعتمدة؟",
      INTERNAL_CONTROL_SYSTEM_APPROVED_BY_BOARD:"هل تم اعتماد نظام الرقابة الداخلي من مجلس الإدارة؟",
      BOARD_OVERSEES_ASSEMBLY_AND_AUDITOR_DECISIONS:"هل يشرف المجلس على تنفيذ قرارات وتعليمات الجمعية العمومية أو المراجع الخارجي؟",
      HAS_APPROVED_CONFLICT_OF_INTEREST_POLICY:"هل توجد سياسة لتعارض المصالح معتمدة من مجلس الإدارة؟",
      HAS_RELATED_PARTY_TRANSACTIONS_BETWEEN_MEMBERS:"هل توجد علاقة تعاقدية أو تجارية من الدرجة الأولى إلى الدرجة الرابعة بين أحد أعضاء الجمعية العمومية أو أعضاء مجلس الإدارة أو موظفي الجمعية؟",
      HAS_APPROVED_WHISTLEBLOWER_PROTECTION_POLICY:"هل توجد سياسة للإبلاغ عن المخالفات وحماية مقدمي البلاغات معتمدة من مجلس الإدارة؟",
      HAS_APPROVED_DATA_PRIVACY_POLICY:"هل توجد سياسة لخصوصية البيانات معتمدة من مجلس الإدارة؟",
      HAS_APPROVED_DOCUMENT_RETENTION_POLICY:"هل توجد سياسة للاحتفاظ بالوثائق وإتلافها معتمدة من مجلس الإدارة؟",
      HAS_APPROVED_DONATION_POLICY:"هل توجد سياسة لجمع التبرعات معتمدة من مجلس الإدارة؟",
      HAS_APPROVED_BENEFICIARY_RELATIONS_POLICY:"هل توجد سياسة لتنظيم العلاقة مع المستفيدين (المستفيدين من الخدمة التي تقدمها الجمعية) معتمدة من مجلس الإدارة؟",
      POLICY_INCLUDES_ELIGIBILITY_VERIFICATION:"هل تحتوي السياسة على آلية للتأكد من استحقاق المستفيد؟",
      BENEFICIARY_NEEDS_ASSESSED:"هل تم دراسة احتياجات المستفيدين؟",
      AID_DISTRIBUTED_FAIRLY_TO_BENEFICIARIES:"هل تم توزيع التبرعات (الخدمات) بشكل عادل ومنصف بين المستفيدين؟",
      AID_MEETS_ACTUAL_BENEFICIARY_NEEDS:"هل تلبي التبرعات (الخدمات) الاحتياجات الفعلية للمستفيدين؟",
      AID_DISTRIBUTION_PROPERLY_DOCUMENTED:"هل تم تسجيل وتوثيق توزيع التبرعات (الخدمات) بطريقة صحيحة وشفافة؟",
      HAS_PERIODIC_AID_DISTRIBUTION_REPORTS:"هل توجد تقارير دورية تفيد بتسليم التبرعات (الخدمات) للمستفيدين؟",
      HAS_APPROVED_VOLUNTEER_MANAGEMENT_POLICY:"هل توجد آلية لإدارة المتطوعين في الجمعية معتمدة من مجلس الإدارة؟",
      HAS_APPROVED_HR_POLICY:"هل توجد لائحة للموارد البشرية في الجمعية معتمدة من مجلس الإدارة؟",
      HAS_APPROVED_BOARD_AUTHORITY_POLICY:"هل توجد لائحة لصلاحيات المجلس والصلاحيات الممنوحة من قبل مجلس الإدارة؟",
      HAS_DETAILED_AUTHORITY_DELEGATION_LIST:"هل توجد قائمة بصلاحيات المجلس والصلاحيات التي فّوضها وإجراءات اتخاذ القرار ومدة التفويض؟",
      BOARD_MONITORS_DELEGATED_AUTHORITIES:"هل يقوم المجلس بمتابعة ممارسة الصلاحيات المفّوضة عبر تقارير المتابعة؟",
      BOARD_MET_FOUR_TIMES_IN_PREVIOUS_YEAR:"هل اجتمع مجلس الإدارة (لا ُيقصد اللجنة التنفيذية) خلال السنة المالية السابقة أربعة اجتماعات على الأقل؟",
      BOARD_MEETINGS_HELD_QUARTERLY:"هل ُعقدت الاجتماعات بشكل منتظم (كل 3 أشهر مرة واحدة على الأقل)؟",
      BOARD_MEMBER_WORKS_IN_MANAGEMENT:"هل يوجد أحد أعضاء مجلس الإدارة يعمل في إدارة الجمعية أو في إحدى وظائفها؟",
      HAS_CENTER_APPROVAL_1:"هل توجد موافقة من المركز؟",
      BOARD_MEMBER_WORKS_IN_SUPERVISORY_AUTHORITY:"هل يوجد أحد أعضاء مجلس الإدارة يعمل في الإدارة المختصة بالإشراف على الجمعية في المركز أو الجهة المشرفة؟",
      HAS_CENTER_APPROVAL_2:"هل توجد موافقة من المركز؟",
      BOARD_MEMBER_EXCEEDED_TWO_CONSECUTIVE_TERMS:"هل يوجد أحد من أعضاء مجلس الإدارة استمر في عضويته لأكثر من دورتين متتاليتين؟",
      HAS_CENTER_APPROVAL_3:"هل توجد موافقة من المركز؟",
      BOARD_MEMBER_FROM_JUDICIARY:"هل يوجد أحد أعضاء مجلس الإدارة من أصحاب الفضيلة في السلك القضائي؟",

      HAS_APPOINTED_EXECUTIVE_DIRECTOR:"هل تم تعيين مدير تنفيذي في الجمعية",
      BOARD_MEMBERS_RECEIVED_ORIENTATION_PROGRAMS:"هل تم تقديم برامج تعريفية مخصصة لأعضاء مجلس الإدارة متعّلقة بعمل الجمعية والواجبات والمهام وفق نظام الجمعيات والمؤسسات الأهلية، وذلك خلال السنة المالية الحالية أو السابقة؟",
      EXECUTIVE_DIRECTOR_APPOINTED_BY_BOARD:"هل تم تعيينه (تعيين وليس تكليف) بقرار من قبل مجلس الإدارة؟",
      EXECUTIVE_DIRECTOR_RESPONSIBILITIES_DEFINED_IN_APPOINTMENT:"هل تم توضيح صلاحياته ومسؤولياته وحقوقه والتزاماته في قرار التعيين؟",
      EXECUTIVE_DIRECTOR_APPOINTMENT_DETAILS_SENT_TO_CENTER:"هل تم إرسال نسخة من قرار التعيين ومسوغات الراتب مع إرفاق صورة من هويته الوطنية وبيانات التواصل معه إلى المركز؟",
      HAS_SAUDI_ACCOUNTANT:"هل يوجد لدى الجمعية محاسب سعودي الجنسية؟",
      ACCOUNTANT_APPOINTMENT_DETAILS_SENT_TO_CENTER:"هل تم إرسال نسخة من قرار التعيين ومسوغات الراتب مع إرفاق صورة من هويته الوطنية وبيانات التواصل معه إلى المركز؟",
      BOARD_TERM_ENDING_OR_RECENTLY_ENDED:"هل مدة دورة مجلس الإدارة انتهت قريبًا (ستة أشهر قبل التقييم) أو على وشك الانتهاء (شهر بعد التقييم)؟",
      ELECTION_COMMITTEE_FORMED_IN_PREVIOUS_ASSEMBLY:"هل تم تشكيل لجنة انتخابات في الاجتماع العمومي الذي يسبق اجتماع الترشيح؟",
      ELECTION_COMMITTEE_HAS_TWO_NONCANDIDATE_MEMBERS:"هل أعضاء لجنة الانتخابات اثنين من أعضاء الجمعية العمومية كحد أدنى وغير مرشحين لعضوية المجلس الجديد؟",
      BOARD_INVITED_ELIGIBLE_CANDIDATES_WITHIN_TIMEFRAME:"هل دعا مجلس الإدارة جميع أعضاء الجمعية العمومية الذين تنطبق عليهم شروط الترشح لعضوية مجلس الإدارة قبل مئة وثمانين يوماً على الأقل من نهاية مدة مجلس الإدارة؟",
      NOMINATIONS_CLOSED_AND_SUBMITTED_TO_CENTER_ON_TIME:"هل تم إقفال باب الترشيح قبل تسعين يوما من نهاية مدة المجلس على الأقل ورفع أسماء المترشحين إلى المركز خلال أسبوع من قفل باب الترشيح؟",
      CANDIDATE_LIST_DISPLAYED_FIFTEEN_DAYS_BEFORE_TERM_END:"هل عرضت لجنة الانتخابات بالتنسيق مع مجلس الإدارة قائمة أسماء المترشحين الواردة من المركز في مقر الجمعية أو موقع الجمعية الإلكتروني قبل خمسة عشر يوما على الأقل من نهاية مدة المجلس؟",
      NEW_BOARD_MEMBERS_SUBMITTED_TO_CENTER_WITHIN_FIFTEEN_DAYS:"هل زود مجلس الإدارة الجديد المركز بأسماء الأعضاء الذين تم انتخابهم خلال خمسة عشر يوما من تاريخ الانتخاب؟",
      HAS_LOCAL_BRANCHES_AND_OFFICES:"هل يوجد لدى الجمعية فروع ومكاتب داخل المملكة؟",
      BRANCHES_APPROVED_BY_CENTER_AND_SUPERVISOR:"هل توجد موافقة من المركز والجهة المشرفة على إنشاء هذه الفروع والمكاتب؟",
      HAS_CERTIFIED_EXTERNAL_AUDITOR:"هل تم التعاقد مع مراجع حسابات معتمد لدى المركز أو مصنف لدى الهيئة السعودية للمراجعين والمحاسبين؟",
      HAS_DETAILED_ANNUAL_FINANCIAL_REPORT_APPROVED:"هل يوجد تقرير سنوي مفصل عن القوائم المالية ومعتمد من مراجع حسابات خارجي ومن الجمعية العمومية؟",
      TERRORISM_FINANCING_RISKS_IDENTIFIED_AND_UNDERSTOOD:"هل قامت الجمعية بتحديد وفهم مخاطر جرائم الإرهاب وتمويله لديها؟",
      USES_CASH_TRANSACTIONS_FOR_DONATIONS:"هل يتم استخدام وسيلة التعاملات النقدية غير الإلكترونية في جمع التبرعات أو صرفها للمستفيدين؟",
      HAS_MONEY_LAUNDERING_SUSPICION_PROCEDURES:"هل لدى الجمعية إجراءات واضحة تلتزم بها إذا توافرت لديهم أسباب معقولة للاشتباه في أن الأموال أو بعضها تمثل عمليات لها علاقة بغسل الأموال أو أنها سوف تستخدم في عمليات غسل أموال أو بعلاقة أو ارتباط أي من العمليات، أو الصفقات المعّقدة، أو الضخمة أو غير الطبيعية بعمليات غسل الأموال؟",
      HAS_TERRORISM_FINANCING_AWARENESS_PROGRAMS:"هل توجد برامج توعوية لنشر وتعميق الوعي داخل الجمعية حول نقاط الضعف الممكنة والتي قد تستغل من قبل ممولي الإرهاب؟",
      REGISTRATION_CERTIFICATE_VALID:"هل شهادة تسجيل الجمعية سارية؟",
      ACTIVITIES_MATCH_CLASSIFICATION:"هل أنشطة الجمعية متطابقة مع تصنيفها؟",
      PROGRAM_ACTIVITIES_APPROVED_BY_SUPERVISORY_UNIT:"هل تمت الموافقة على طلبات إقامة البرامج والمشروعات والأنشطة الفنية التي تقدمها الجمعية وفق الإجراءات المتبعة للوحدة الإشرافية التابعة لها؟",
      HAS_UNAUTHORIZED_ACTIVITIES_OUTSIDE_BYLAWS:"هل توجد برامج وأنشطة للجمعية متعارضة مع أهدافها المحّددة في اللائحة الأساسية وبدون موافقة من المركز؟",
      HAS_SERVICE_DELIVERY_TRACKING_DOCUMENTATION:"هل يوجد توثيق لتتبع وصول الخدمة والمساعدات للمستفيدين؟",
      HAS_ACTIVITIES_OUTSIDE_ADMINISTRATIVE_SCOPE:"هل لدى الجمعية برامج أو أنشطة خارج نطاقها الإداري؟",
      HAS_CENTER_APPROVAL_4:"هل توجد موافقة من المركز؟",
      HAS_INTERNATIONAL_PARTNERSHIPS_OR_AGREEMENTS:"هل توجد تعاقدات أو شراكات أو اتفاقيات مع دول أو منظمات أو مؤسسات دولية؟",
      HAS_APPROVAL_FOR_INTERNATIONAL_AGREEMENTS:"هل توجد موافقة على ذلك من المركز والجهة المختصة؟",
      CONDUCTS_FUNDRAISING_CAMPAIGNS:"هل تقوم الجمعية بحملات لجمع التبرعات؟",
      HAS_FUNDRAISING_APPROVAL_FROM_CENTER:"هل توجد موافقة من المركز بذلك؟",
      HAS_SEPARATE_DONATIONS_ACCOUNT:"هل يوجد حساب مستقل للتبرعات؟",
      HAS_DONATIONS_REGISTRY:"هل يوجد سجل خاص بالتبرعات؟",
      DONATION_REGISTRY_INCLUDES_REQUIRED_DETAILS:"هل يحتوي السجل معلومات المتبرع، وقيمة التبرع، وشرطه إن وجد؟",
      DONATIONS_USED_FOR_UNINTENDED_PURPOSE:"هل تم استخدام التبرعات التي تم جمعها لغرض معين في نشاط آخر غير ما ُجمعت لأجله؟",
      HAS_CENTER_APPROVAL_FOR_DONATION_REPURPOSE:"هل توجد موافقة من المركز على ذلك؟",
      SURPLUS_INVESTED_IN_ENDOWMENTS_OR_PROJECTS:"هل تم استخدام فائض إيرادات معّينة وإدخالها في أوقاف الجمعية، أو تم استثمارها في مجالات مرّجحة الكسب تضمن لها الحصول على مورد ثابت، أو تم إعادة توظيفها في المشروعات الإنتاجية والخدمية؟",
      SURPLUS_INVESTMENT_APPROVED_BY_ASSEMBLY:"هل تم أخذ موافقة الجمعية العمومية على ذلك؟",
      RECEIVED_UNSOLICITED_FOREIGN_AID:"هل استقبلت الجمعية أعانات من خارج المملكة من دون طلب؟",
      NOTIFIED_CENTER_OF_FOREIGN_AID:"هل تم ابلاغ المركز؟",
      HAS_PROPERTY_OR_INVESTMENTS:"هل توجد عقارات أو استثمارات في ملكية الجمعية؟",
      PROPERTY_ACQUISITION_PROPERLY_APPROVED:"هل توجد موافقة من الجمعية العمومية قبل التملك أو تم إقرار ذلك في أول اجتماع تاٍل لها أو بقرار من مجلس الإدارة -في حال تم تفويضه من الجمعية العمومية باتخاذ القرارات في ذلك؟",
      BENEFICIARY_RECORDS_SECURELY_MAINTAINED:"هل يتم الاحتفاظ في مقر الجمعية بسجلات المستفيدين بحيث لا يتم فقدانها أو كشف سريتها؟",
      HAS_UPDATED_ASSEMBLY_MEETINGS_REGISTRY:"هل يوجد سجل محّدث خاص بوقائع جلسات الجمعية العمومية العادية وغير العادية؟",
      BOARD_MEETING_RECORDS_MAINTAINED:"هل ُتحفظ السجلات المتعلقة باجتماعات مجلس الإدارة؟",
      MEMBERS_HAVE_MEMBERSHIP_CARDS:"هل توجد بطاقات عضوية لكل عضو من أعضاء الجمعية العمومية؟",
      ALL_MEMBERS_RECEIVED_MEMBERSHIP_CARDS:"هل استلم جميع أعضاء الجمعية العمومية بطاقات عضوية؟",
      HAS_PERMANENT_OR_TEMPORARY_COMMITTEES_WITH_SPECIFIC_TASKS:"هل توجد لجان دائمة أو مؤقتة تم تكوينها من قبل الجمعية العمومية أو مجلس الإدارة للقيام بمهام محددة من حيث طبيعتها ومدتها؟",
      COMMITTEES_FORMATION_DECISIONS_EXIST:"هل توجد قرارات صادرة بتكوين هذه اللجان؟",
      COMMITTEE_DECISIONS_INCLUDE_COMPLETE_DETAILS:"هل اشتملت القرارات على مسمى كل لجنة وعدد أعضائها واختصاصاتها واختصاصات أعضائها، بما في ذلك تسمية رئيسها؟",
      BOARD_MEMBERS_PRESENT_IN_COMMITTEES:"هل يوجد أحد أعضاء مجلس الإدارة في هذه اللجان؟",
      HAS_EXECUTIVE_COMMITTEE:"هل توجد لجنة تنفيذية في الجمعية؟",
      EXECUTIVE_COMMITTEE_FORMED_WITH_DEFINED_AUTHORITIES:"هل يوجد قرار بتشكيلها وتحديد المهام والصلاحيات المفوضة فيها والتي تكفل سير عمل الجمعية؟",
      HAS_INTERNAL_AUDIT_COMMITTEE:"هل توجد لجنة تدقيق ومراجعة داخلية؟",

      FINANCIAL_SUPERVISOR_CHAIRS_AUDIT_COMMITTEE:"هل يرأس المشرف المالي في مجلس الإدارة هذه اللجنة؟"
    }

}

export { entriesLabels, indicatorsLabels, dashboardStatusMap, tabsNames ,governanceLabels,GOVERANCE_TABS};
