const dashboardStatusMap = {
  NOT_STARTED: "لم يتم البدء",
  IN_PROGRESS: "قيد التنفيذ",
  COMPLETED: "مكتمل",
};

const tabsNames = {
  FINANCIAL: "مؤشر الأداء المالي",
  OPERATIONAL: "مؤشر الأداء التشغيلي",
  CORPORATE: "مؤشر الأداء المؤسسي",
  GENERAL: "اللوحة العامة",
};

const entriesLabels = {
  FINANCIAL: {
    GENERAL_ADMINSTRATIVE_EXPENSES: "المصاريف العمومية و الإدارية",
    GOVERENCE_EXPENSES: "مصاريف الحوكمة",
    PROGRAMS_EXPENSES_BOUNDED: "مصاريف برامج و أنشطة مقيدة",
    PROGRAMS_EXPENSES_UNBOUNDED: "مصاريف برامج و أنشطة غير مقيدة",
    PROGRAMS_EXPENSES: "مصاريف البرامج",
    GENERAL_ADMINSTRATIVE_EXPENSES_ACT:
      "مصاريف العمومية و الإدارية المحملة على البرامج والأنشطة",
    AWQAF_EXPENSES: "مصاريف الأوقاف",
    INVESTMENT_EXPENSES: "مصاريف الاستثمار",
    SUSTAINBILITY_EXPENSES: "مصاريف الاستدامة",
    FUND_RAISING_EXPENSES: "مصاريف جمع الأموال",
    TOTAL_EXPENSES: "إجمالي المصاريف",
    AWQAF_REVENUE: "إيرادات الأوقاف",
    INVESTMENT_REVENUE: "إيرادات الاستثمارات",
    SUSTAINBILITY_REVENUE: "إيرادات الاستدامة المالية",
    BOUNDED_CHARITY: "التبرعات المقيدة",
    UNBOUNDED_CHARITY: "تبرعات غير مقيدة",
    TOTAL_CHARITY: "إجمالي التبرعات",
    CASH_RELATED: "النقد وما في حكمه",
    TRADED_INVESTMENTS: "الاستثمارات المتداولة",
    SUSTAIN_ASSETS_WAQFI: "الأصول الاستدامة الوقفية",
    SUSTAIN_ASSETS_INVEST: "أصول الاستدامة  الاستثمارات",
    SUSTAIN_ASSETS_FIN: "أصول الاستدامة المالية",
    CURRENT_LIABILITIES: "الالتزامات المتداولة",
    BOUNDED_NET_ASSETS: "صافي الأصول المقيدة",
    AWQAF_NET_ASSETS_CASH: "صافي أصول الأوقاف)نقدية)",
    GOV_PLATFORMS_REVENUE: "الإيرادات من المنصات الحكومية",
    PRGMS_PRJKS_REVENUE: "عوائد البرامج والمشاريع",
    NO_PAID_MEMBERSHIP: "عدد العضويات المسددة",
    TOTAL_MEMBERSHIP: "إجمالي العضويات",
    FIN_VALUE_VOLUN: "القيمة المالية لساعات التطوع",
    OPERATIONAL_EXPANSES: "المصروفات التشغيلية",
    LAST_YEAR_REVENUE: "إيرادات العام السابق",
    NO_CONT_VOLUN: "عدد المتبرعين المستمرين",
    NO_TOTAL_VOLUN_LAST_YEAR: "إجمالي المتبرعين في العام السابق",
    NO_TOTAL_MONEY_VAT: "إجمالي المبالغ المستردة من الضريبة",
    START_LIABILITIES: "الالتزامات في بداية العام",
    END_LIABILITIES: "الالتزامات في نهاية العام",
  },
  CORPORATE: {
    COMPLIANCE_ADHERENCE_PRACTICES: "ممارسات الامتثال و الالتزام",
    TRANSPARENCY_DISCLOSURE_PRACTICES: "ممارسات الشفافية و الإفصاح",
    FINANCIAL_SAFETY_PRACTICES: "ممارسات السلامة المالية",
    NO_SUCCESSFUL_HIRES_POST_EXP:
      "عدد التعيينات الناجحة التي تجاوزت فترة التجربة",
    TOTAL_HIRES: "إجمالي التعيينات",
    PERC_COMMIT_WORK_HOURS: "نسبة الالتزام بالدوام الرسمي",
    NO_EXE_PRACTICES: "عدد التدريبات المنفذة",
    NO_PLANNED_PRACTICES: "عدد التدريبات المخططة",
    NO_COMP_ELEMENTS: "عدد العناصر المكتملة في الخطة",
    TOTAL_ELEMENTS: "إجمالي العناصر",
    NO_TIMELY_REPORTS: "عدد التقارير المنجزة في موعدها",
    NO_REQUIRED_REPORTS: "عدد التقارير المطلوبة",
    NO_GRADES_BENEFITS_SATISF: "مجموع درجات الرضا المستفيدين",
    NO_RESPONSES_SATIS_FORM: "عدد المستجيبين من استبيان رضا المستفيدين",
    TOTAL_GRADES_EMP_SATIS: "مجموع درجات رضا الموظفين",
    NO_RESPONSES_EMP_SATIS: "عدد المستجيبين من استبيان رضا الموظفين",
    TOTAL_GEADES_PARTENERS_SATIS: "مجموع درجات رضا الشركاء والموردين",
    NO_RESPONSES_PARTERS_FORM: "عدد المستجيبين من استبيان الشركاء والموردين",
    TOTAL_RESPONSES_VOL_SATIS: "مجموع درجات رضا المتطوعين",
    TOTAL_GRADES_VOL_STATIS: "مجموع درجات رضا المتطوعين",
    TOTAL_GRADES_DON_STATIS: "مجموع درجات رضا المتبرعين",
    NO_RESPOSES_VOL_SATIS_FORM: "عدد المستجيبين من استبيان رضا المتطوعين",
    NO_RESPONSES_VOL_SATIS_FORM: "عدد المستجيبين من استبيان رضا المتطوعين",
    NO_RESPONSES_DON_SATIS_FORM: "عدد المستجيبين من استبيان رضا المتبرعين",
    TOTAL_SATIS_GRADES_ORG: "مجموع درجات الرضا الجمعية العمومية ومجلس الإدارة",
    NO_ORG_MEMBERS: "العدد الكلي للأعضاء الجمعية العمومية ومجلس الإدارة",
    TOTAL_GRADES_COM: "مجموع درجات رضا المجتمع",
    NO_RESPONSES_COM_SATIS: "عدد المستجيبين من استبيان رضا المجتمع",
    TASKS_ACHIEVED_TIMELY_CEO: "المهام المنجزة في وقتها للمدير التنفيذي",
    TOTAL_PLANNED_TASKS_CEO: "إجمالي المهام المخططة للمدير التنفيذي",
    AVG_EVAL_EMPS: "متوسط تقييم أداء جميع الموظفين",
    AVG_RES_SATIS_FORMS_EMP:
      "متوسط نتائج استبيانات الرضا الموظفين، الشركاء، أصحاب المصلحة",
    EMP_EVAL: "تقييم كل موظف",
    EMP_ACHIEVMENT_PERC: "نسبه إنجاز كل موظف",
    NO_EXEC_DESC: "عدد القرارات المنفذة",
    TOTAL_DESC: "إجمالي القرارات",
    NO_ACHIV_TARGETS: "عدد الأهداف المحققة",
    TOTAL_TARGETS: "إجمالي الأهداف",
  },
  OPERATIONAL: {
    NO_OPERATIONAL_GOALS_ACHIEVED: "عدد الأهداف التشغيلية المحققة",
    NO_OPERATIONAL_GOALS_PLANNED: "إجمالي الأهداف التشغيلية المخططة",
    NO_PROGRAMS_EXECUTED: "عدد البرامج المنفذة",
    NO_PROGRAMS_PLANNED: "إجمالي البرامج المخططة",
    NO_TIMELY_ACTIVITIES: "عدد الأنشطة المنفذة في وقتها",
    TOTAL_PLANNED_ACTIVITIES: "إجمالي الأنشطة المخططة",
    APPROVED_BUDGET: "الميزانية المعتمدة",
    PLANNED_ACTUAL_DIFF: "الفرق بين المخطط والفعلي",
    NO_OUTPUTS_ACHIEVED: "عدد المخرجات المحققة بالمواصفات المطلوبة",
    TOTAL_TARGETED_OUTPUTS: "إجمالي المخرجات المستهدفة",
    NO_ACTUAL_BENEFICIARIES: "عدد المستفيدين الفعلي",
    PLANNED_TARGET_NUMBER: "العدد المستهدف في الخطة",
    NO_PROGRAMS_WITH_PARTICIPANTS:
      "عدد المشاريع والبرامج التي شارك فيها متطوعون",
    NO_PROGRAMS_PROJECTS: "إجمالي عدد المشاريع والبرامج",
    NO_TIMELY_TRANSACTIONS: "عدد المعاملات المنجزة خلال الوقت المحدد",
    TOTAL_TRANSACTIONS: "إجمالي المعاملات",
    NO_ARCHIVED_DOCS: "عدد الوثائق المؤرشفة حسب النظام",
    TOTAL_DOCS: "إجمالي الوثائق",
    NO_VOLUNTEERS_CURRENT_QUARTER: "عدد المتطوعين في الربع الحالي",
    NO_VOLUNTEERS_NEXT_QUARTER: "عدد المتطوعين في الربع السابق",
    NO_VOLUNTEERS_CONT_3: "عدد المتطوعين المستمرين لأكثر من 3 أشهر",
    TOTAL_VOLUNTEERS: "إجمالي عدد المتطوعين",
  },
  GENERAL: {
    NO_ADOPTED_ORPHANS: "عدد الأيتام المكفولين ",
    TOTAL_TARGETED_ORPHANS: "إجمالي الأيتام المستهدفين",
    TOTAL_MONTHLY_ADOP_EXP: "إجمالي تكاليف الكفالات الشهرية ",
    NO_ORPHANS_PRGM: "عدد الأيتام المشاركين في البرامج التأهيلية ",
    TOTAL_ORPHANS_QUAL_PRGM: "إجمالي الأيتام المؤهلين للبرامج التأهيلية",
    TOTAL_ANNUAL_EXP_ORPHANS: "إجمالي تكاليف الخدمات السنوية",
    NO_BENF_ORPHANS: "عدد الأيتام المستفيدين من الخدمات",
    NO_STD_ORPHANS: "عدد الأيتام الملتحقين بالتعليم العام ",
    TOTAL_ORPHANS_STD_AGE: "إجمالي الأيتام في سن التعليم العام",
    NO_ORPHANS_STD_UNI: "عدد الأيتام الملتحقين بالتعليم الجامعي ",
    TOTAL_ORPHANS_AGE_UNI: "إجمالي الأيتام في سن التعليم الجامعي",
    TOTAL_MARKS_ORPHANS: "مجموع المعدلات الدراسية لجميع الأيتام ",
    NO_GEN_EDU_ORPHANS: "عدد الأيتام الملتحقين بالتعليم",
    NO_HLTH_ORPHANS: "عدد الأيتام المشمولين بالتأمين الصحي ",
    TOTAL_ORPHANS: "إجمالي الأيتام",
    NO_EXEC_CONST_REQS: "عدد طلبات الصيانة المنفذة ",
    TOTAL_CONST_REQS: "إجمالي طلبات الصيانة المستلمة",
    NO_MOSQUES_ND_CONST: "عدد المساجد المحتاجة للترميم ",
    TOTAL_REG_MOSQUES: "إجمالي المساجد المسجلة",
    NO_MOSQUES_COMP_CONST: "عدد المساجد المكتملة البناء ",
    TOTAL_MOSQUES_PLAN_CONST: "إجمالي المساجد المخطط بناؤها",
    TOTAL_ANNUAL_EXPANSES_MOSQUES: "إجمالي تكاليف الصيانة السنوية ",
    NO_SERV_MOSQUES: "عدد المساجد المخدومة",
    NO_RESV_COMPL_MOSQUES: "عدد الشكاوى المستلمة ",
    NO_EXEC_PRJKS_MOSQUES: "عدد المشاريع المنفذة    ",
  },
};

const indicatorsLabels = {
  FINANCIAL: {
    FINANCIAL_PERF:"الأداء المالي",
    FINANCIAL_RESOURCES_DEV: "تنمية الموارد المالية",
    ADMIN_EXPENSES: "المصاريف الإدارية  ",
    PRGRMS_EXPENSES: "مصاريف البرامج و الأنشطة",
    FINANCIAL_SUSTAIN: " نسبة الاستدامة المالية ",
    DONAT_MONEY_RAISING: "جمع الأموال و التبرعات",
    ABL_COVER_OBLIG: "القدرة على تغطية التزاماتها المستقبلية",
    DIVERSITY_INCOME_RESOURCES:"تنوع مصادر الدخل",
    EFFECIENT_RESOURCE_MGMT:"كفاءة إدارة الموارد",
    ADMIN_TO_TOTAL_EXPENSES:"المصاريف الإدارية إلى اجمالي المصاريف",
    REV_FIN_SUST_TO_TOTAL_EXPENSES:"عوائد الاستدامة المالية إلى المصاريف الإدارية",
    PRGRMS_TO_TOTAL_EXPENSES:"مصاريف البرامج والأنشطة إلى اجمالي المصاريف",
    SUST_TO_TOTAL_EXPENSES:"مصاريف الاستدامة إلى اجمالي المصاريف",
    SUST_EXPENSEES_TO_REV:"مصاريف الاستدامة إلى عوائد الاستدامة",
    SUST_RETURN_TO_ASSETS:"العائد من الاستدامة إلى اجمالي أصول الاستدامة",
    FUND_RAISING_TO_TOTAL_EXPENSES:"مصاريف جمع الأموال إلى اجمالي المصاريف",
    FUND_RAISING_TO_TOTAL_DONAT:"مصاريف جمع الأموال إلى اجمالي التبرعات",
    CACHE_RELATED_TO_NET_ASSETS_AND_AWQAF:"النقد وما ي حكمه إلى (صافي الأصول المقيدة + صافي أصول النقدية الأوقاف)",
    NET_CACHE_INVEST_ADMIN_EXPENSES:"صافي النقد والاستثمارات المتداولة إلى المصاريف الإدارية التقديرية",
    DONAT_PERC:"نسبة التبرعات (مقيدة/غير مقيدة)",
    PLATFORM_REV_PERC:"نسبة الإيرادات من المنصات",
    PRGMS_PRJKS_REV:"عوائد البرامج و المشاريع",
    PAID_MEMBERSHIP_PERC:"نسبة العضويات المسددة",
    ECO_RETURN_VOLUN:"العائد الاقتصادي من التطوع",
    RATE_REV_ANNUAL_GROWTH:"معدل نمو الإيرادات السنوي",
    COMMIT_DISC_PERC:"نسبة تخفيض الالتزامات",
    RATE_SUST_DONAT:"معدل استدامة المتبرعين",
    TOTAL_TAX_REFUND:"اجمالي المبالغ المستردة من الضريبة"
  },
  CORPORATE: {
    CORORATE_PERFORMANCE: "الأداء المؤسسي ",
    GOVERANCE: "النسبة الإجمالية للحوكمة",
    HR: "الموارد البشرية",
    PLANNING_ORGANIZING: "التخطيط والتنظيم",
    SATIS_MEASURMENT: "قياس الرضا",
    CEO_PERFORMANCE: "أداء المديرالتنفيذي ",
    COMPLIANCE_ADHERENCE_PRACTICES: "ممارسات الامتثال و الالتزام",
    TRANSPARENCY_DISCLOSURE_PRACTICES: "ممارسات الشفافية و الإفصاح",
    FINANCIAL_SAFETY_PRACTICES: "ممارسات السلامة المالية",
    RECRUITMENT: "التوظيف والاستقطاب",
    EMP_PERF_PROD: "أداء وإنتاجية الموظفين",
    EMP_DEV_TRAIN: "تطوير وتدريب الموظفين",
    TARGETS_HIT_PERF_EVAL: "تحقيق المستهدفات و تقييم الأداء ",
    JOB_COMMITMENT: "الانضباط الوظيفي",
    TRAIN_PLAN_EXEC: "تنفيذ خطة التدريب",
    TRAIN_IMPACT: "أثر التدريب",
    FOLLOWUP_OPERATIONAL_PLAN: "متابعة الخطة التشغيلية",
    QUALITY_OPERATIONAL_PLAN: "جودة الخطة التشغيلية",
    BENEF_SATIS_MEASURMENT: "قياس رضا المستفيدين",
    EMP_SATIS_MEASURMENT: "قياس رضا الموظفين",
    PARTENERS_SATIS_MEASURMENT: "قياس رضا الشركاء والموردين",
    VOLUN_SATIS_MEASURMENT: "قياس رضا المتطوعين",
    DONATORS_SATIS_MEASURMENT: "قياس رضا المتبرعين والداعمين ",
    ADMIN_ORG_SATIS_MEASURMENT: "قياس رضا الجمعية العمومية ومجلس الإدارة ",
    COMMUNITY_SATIS_MEASURMENT: "قياس رضا المجتمع والصورة الذهنية",
    EXEC_LEADERSHIP: "القيادة التنفيذية ",
    OPERATIONAL_PERF: "القيادة التنفيذية ",
    ENTERPRISE_COMMUN: "القيادة التنفيذية ",
    FOLLOWUP_BOARD_DECISION: "متابعة تنفيذ قرارات مجلس الإدارة",
    OPERATIONAL_PLAN_ACHIVMENT_GOALS: "تحقيق مستهدفات الخطة التشغيلية",
    DAILY_OPS_MGMT: "إدارة العمليات اليومية",
    FOLLOWUP_EMPS_PERF: "متابعة أداء الموظفين",
  },
  OPERATIONAL: {

    EFFIC_INTERNAL_OPS: "كفاءة العمليات الداخلية",
    VOLN_MGMT: "إدارة التطوع",
    OPS_PLAN_EXEC: "تنفيذ الخطة التشغيلية",
    PRJKT_PRGM_MGMT: "إدارة المشاريع والبرامج",
    OPS_GOALS_ACH_PERC: "نسبة تحقيق الأهداف التشغيلية",
    PGRM_PRJKS_EXEC_PERC: "نسبة تنفيذ البرامج والمشاريع",
    EFFIC_PRJKS_EXEC: "كفاءة تنفيذ المشاريع",
    EFFITV_PRJKS_PGRM: "فعالية المشاريع والبرامج",
    VOLN_CONTR_PRJKS_EXEC: "مساهمة المتطوعين في تنفيذ المشاريع",
    QLY_SPEED_PROC_EXEC: "جودة وسرعة تنفيذ الإجراءات",
    DOCS_ARCHIV: "التوثيق والأرشفة",
    VOLUN_GROWTH_RATE_QUAR: "معدل النمو الربعي للمتطوعين",
    VOLUN_SUST_PERC: "نسبة استدامة المتطوعين",
    PRJKT_TIMELY_COMP_PERC: "نسبة إنجاز المشروع في الوقت المحدد",
    BUDGET_COMMIT_PERC: "نسبة الالتزام بالميزانية",
    PRJK_GOALS_ACHV_PERC: "نسبة تحقيق أهداف المشروع",
    REACH_TARGET_AUD_PERC: "نسبة الوصول للفئة المستهدفة"

  },
  GENERAL: {},
};

export { entriesLabels, indicatorsLabels, dashboardStatusMap, tabsNames };
