const operationalEntries = {
    NO_OPERATIONAL_GOALS_ACHIEVED:"عدد الأهداف التشغيلية المحققة",
    NO_OPERATIONAL_GOALS_PLANNED:"إجمالي الأهداف التشغيلية المخططة",
    NO_PROGRAMS_EXECUTED:"عدد البرامج المنفذة",
    NO_PROGRAMS_PLANNED:"إجمالي البرامج المخططة",
    NO_TIMELY_ACTIVITIES:"عدد الأنشطة المنفذة في وقتها",
    TOTAL_PLANNED_ACTIVITIES:"إجمالي الأنشطة المخططة",
    APPROVED_BUDGET:"الميزانية المعتمدة",
    PLANNED_ACTUAL_DIFF:"الفرق بين المخطط والفعلي",
    NO_OUTPUTS_ACHIEVED:"عدد المخرجات المحققة بالمواصفات المطلوبة",
    TOTAL_TARGETED_OUTPUTS:"إجمالي المخرجات المستهدفة",
    NO_ACTUAL_BENEFICIARIES:"عدد المستفيدين الفعلي",
    PLANNED_TARGET_NUMBER:"العدد المستهدف في الخطة",
    NO_PROGRAMS_WITH_PARTICIPANTS:"عدد المشاريع والبرامج التي شارك فيها متطوعون",
    NO_PROGRAMS_PROJECTS:"إجمالي عدد المشاريع والبرامج",
    NO_TIMELY_TRANSACTIONS:"عدد المعاملات المنجزة خلال الوقت المحدد",
    TOTAL_TRANSACTIONS:"إجمالي المعاملات",
    NO_ARCHIVED_DOCS:"عدد الوثائق المؤرشفة حسب النظام",
    TOTAL_DOCS:"إجمالي الوثائق",
    NO_VOLUNTEERS_CURRENT_QUARTER:"عدد المتطوعين في الربع الحالي",
    NO_VOLUNTEERS_NEXT_QUARTER:"عدد المتطوعين في الربع السابق",
    NO_VOLUNTEERS_CONT_3:"عدد المتطوعين المستمرين لأكثر من 3 أشهر",
    TOTAL_VOLUNTEERS:"إجمالي عدد المتطوعين",
}

export {operationalEntries}