name = "dashbaord-fe"
compatibility_date = "2024-11-18"
pages_build_output_dir = "./build/client"
compatibility_flags = [ "nodejs_compat" ]

[[r2_buckets]]
binding = "KEDAN_DASHBOARD_BUCKET"
bucket_name = "kedan-dashboard-bucket"
