export const USER_MGMT = {
  PAGE_TITLE: "إدارة المستخدمين",
  PAGE_DESCRIPTION: "قم بإدارة أعضاء فريقك وأذونات حساباتهم هنا.",
  CREATE_CLIENT: "إضافة جمعية جديدة",
  EDIT_CLIENT: "تعديل بيانات الجمعية",
  FORM_FIELDS: {
    name: "اسم الجمعية",
    phoneNumber: "رقم الجوال",
    email: "البريد الإلكتروني",
    type: "تصنيف الجمعية",
    licenseNumber: "رقم الترخيص",
    website: "الموقع الإلكتروني",
    address: "العنوان الوطني",
    city: "المدينة",
    neighbor: "الحي",
    street: "الشارع",
    map: "خارطة الجمعية (رابط أو تحميل ملف)",
    repName: "الاسم",
    repPhoneNumber: "الجوال",
    repEmail: "الايميل",
    logo: "شعار الجمعية",
    officialDocs: "المستندات الرسمية",
    operationalPlanImage: "صورة من الخطة التشغيلية",
    repSpeach: "خطاب التمثيل للممثل الرسمي",
    licenseImage: "صورة من الرخصة",
    contractImage: "صورة من العقد",
    additionalDocs: "مستندات إضافية",
    financialIndicatorsSetting: "مؤشر لوحة الأداء المالي",
    operationalIndicatorsSetting: "مؤشر لوحة التشغيل المؤسسي",
    corporateIndicatorsSetting: "مؤشر لوحة حساب الأداء التشغيلي",
    generalndicatorsSetting: "مؤشر حساب اللوحة العامة",
  },
};
