export const USER_MGMT = {
  PAGE_TITLE: "إدارة الجمعيات",
  PAGE_DESCRIPTION: "قم بإدارة بيانات الجمعيات ولوح المعلومات المرتبطة.",
  CREATE_CLIENT: "إضافة جمعية جديدة",
  EDIT_CLIENT: "تعديل بيانات الجمعية",
  DASHBOARD_TYPE:{
    FINANCIAL_DASHBOARD:"مالية",
    CORPORATE_DASHBOARD:"مؤسسية",
    OPERATIONAL_DASHBOARD:"تشغيلية",
    GENERAL_DASHBOARD:"عامة",
    GOVERNANCE_DASHBOARD:"حوكمة"
  },
  FORM_FIELDS: {
    name: "اسم الجمعية",
    phoneNumber: "رقم الجوال",
    email: "البريد الإلكتروني",
    type: "تصنيف الجمعية",
    category:"تخصص الجمعية",
    licenseNumber: "رقم الترخيص",
    website: "الموقع الإلكتروني",
    address: "العنوان الوطني",
    city: "المدينة",
    neighbor: "الحي",
    street: "الشارع",
    map: "خارطة الجمعية (رابط أو تحميل ملف)",
    repName: "الاسم",
    repPhoneNumber: "الجوال",
    repEmail: "الايميل",
    logo: "شعار الجمعية",
    officialDocs: "المستندات الرسمية",
    operationalPlanImage: "صورة من الخطة التشغيلية",
    repSpeach: "خطاب التمثيل للممثل الرسمي",
    licenseImage: "صورة من الرخصة",
    contractImage: "صورة من العقد",
    additionalDocs: "مستندات إضافية",
    financialIndicatorsSetting: "مؤشر لوحة الأداء المالي",
    operationalIndicatorsSetting: "مؤشر لوحة التشغيلي ",
    corporateIndicatorsSetting: "مؤشر لوحة حساب الأداء  المؤسسي ",
    generalndicatorsSetting: "مؤشر حساب اللوحة العامة",
    governanceIndicatorsSetting:"مؤشر حساب لوحة الحوكمة",
    allDashboardsSetting:"مؤشر حساب اللوحات"
  },
  OPTIONS:{
    technical:"تقني",
    waqfi:"وقفي",
    mosques:"العناية بالمساجد",
    orphans:"رعاية الأيتام",
    none:"لا يوجد"
  }
};
