
export enum DashboardEnum {
    FINANCIAL_DASHBOARD = "FINANCIAL_DASHBOARD",
    CORPORATE_DASHBOARD = "CORPORATE_DASHBOARD",
    OPERATIONAL_DASHBOARD = "OPERATIONAL_DASHBOARD",
    GENERAL_DASHBOARD = "GENERAL_DASHBOARD",
  }


 export type  TGovernanceEntries = "COMPLIANCE_ADHERENCE_PRACTICES" | "TRANSPARENCY_DISCLOSURE_PRACTICES" |"FINANCIAL_SAFETY_PRACTICES"