
export enum DashboardEnum {
    FINANCIAL_DASHBOARD = "FINANCIAL_DASHBOARD",
    CORPORATE_DASHBOARD = "CORPORATE_DASHBOARD",
    OPERATIONAL_DASHBOARD = "OPERATIONAL_DASHBOARD",
    GENERAL_DASHBOARD = "GENERAL_DASHBOARD",
  }